name: Build Android App Bundle (AAB) for Play Store

on:
  push:
    tags:
      - 'v*' # Trigger on version tags
  workflow_dispatch: # Allow manual trigger

jobs:
  build-android-aab:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'vaspitac-app/package-lock.json'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      working-directory: vaspitac-app
      run: npm ci

    - name: Create environment.ts from secrets
      working-directory: vaspitac-app
      run: |
        cat <<EOF > src/environments/environment.ts
        export const environment = {
          production: true,
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }
        }
        EOF
      
    - name: Build Angular app
      working-directory: vaspitac-app
      run: npm run build -- --configuration production
      
    - name: Sync Capacitor
      working-directory: vaspitac-app
      run: npx cap sync
      
    - name: Create google-services.json from secret
      working-directory: vaspitac-app/android/app
      run: |
        echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json
      
    - name: Make gradlew executable
      working-directory: vaspitac-app/android
      run: chmod +x gradlew
      
    - name: Clean previous Android build
      working-directory: vaspitac-app/android
      run: ./gradlew clean
      
    - name: Build Android App Bundle (AAB)
      working-directory: vaspitac-app/android
      run: ./gradlew bundleProductionRelease
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: vaspitac-app-aab
        path: vaspitac-app/android/app/build/outputs/bundle/productionRelease/app-production-release.aab
        retention-days: 90
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: vaspitac-app/android/app/build/outputs/bundle/productionRelease/app-production-release.aab
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 