name: 'Setup Firebase CLI'
description: 'Setup Firebase CLI for deployment operations'

inputs:
  working-directory:
    description: 'Working directory for operations'
    required: false
    default: 'vaspitac-app'
  firebase-project:
    description: 'Firebase project ID'
    required: true
  environment:
    description: 'Environment type (development/production)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Firebase CLI
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm install -g firebase-tools
        firebase --version

    - name: Verify Firebase CLI installation
      shell: bash
      working-directory: ${{ inputs.working-directory }}/firebase
      run: |
        echo "✅ Firebase CLI installed and ready for ${{ inputs.firebase-project }}"
        echo "📁 Working directory: $(pwd)"
        echo "🔧 Project will be set during deployment with authentication" 