name: 'Setup Firebase CLI'
description: 'Setup Firebase CLI for deployment operations'

inputs:
  working-directory:
    description: 'Working directory for operations'
    required: false
    default: 'vaspitac-app'
  firebase-project:
    description: 'Firebase project ID'
    required: true
  environment:
    description: 'Environment type (development/production)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Firebase CLI
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm install -g firebase-tools
        firebase --version

    - name: Setup Firebase project
      shell: bash
      working-directory: ${{ inputs.working-directory }}/firebase
      run: |
        # Set the project
        firebase use ${{ inputs.firebase-project }}
        
        echo "✅ Firebase CLI configured for ${{ inputs.firebase-project }}" 