name: 'Setup Firebase Environment'
description: 'Setup Firebase CLI and create environment configuration'

inputs:
  environment:
    description: 'Environment type (development/production)'
    required: true
  working-directory:
    description: 'Working directory for operations'
    required: false
    default: 'vaspitac-app'
  firebase-project:
    description: 'Firebase project ID'
    required: true
  firebase-token:
    description: 'Firebase token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Firebase CLI
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm install -g firebase-tools
        firebase --version

    - name: Create environment.ts from secrets
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        cat <<EOF > src/environments/environment.ts
        export const environment = {
          production: ${{ inputs.environment == 'production' }},
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }
        }
        EOF
        echo "✅ Environment created for ${{ inputs.environment }}"

    - name: Setup Firebase project
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        firebase use ${{ inputs.firebase-project }}
        firebase auth:export --project ${{ inputs.firebase-project }} --token "${{ inputs.firebase-token }}" || echo "Auth export not needed"
        echo "✅ Firebase authentication configured" 