name: 'Firebase Hosting Setup'
description: 'Setup Firebase CLI and authenticate for hosting deployment'

inputs:
  service-account-key:
    description: 'Firebase service account key JSON'
    required: true
  project:
    description: 'Firebase project ID to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Firebase CLI
      shell: bash
      run: |
        echo "🔧 Installing Firebase CLI..."
        npm install -g firebase-tools
        
    - name: Setup Firebase Authentication
      shell: bash
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
      run: |
        echo "🔐 Setting up Firebase authentication..."
        # Create service account key file
        echo '${{ inputs.service-account-key }}' > serviceAccountKey.json
        
        # Verify the service account key file was created
        echo "📁 Service account key file created:"
        ls -la serviceAccountKey.json
        
        echo "✅ Service account key created and environment variable set"
        
    - name: Set Firebase Project
      shell: bash
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
      run: |
        echo "🎯 Firebase project will be set to: ${{ inputs.project }}"
        echo "✅ Project will be specified in deploy command"
        
    - name: Verify Authentication
      shell: bash
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
      run: |
        echo "✅ Verifying Firebase authentication..."
        echo "🎯 Project will be: ${{ inputs.project }}"
        echo "🔑 Service account authentication ready"
        echo "🎉 Firebase hosting setup complete!"
