name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'vaspitac-app/package-lock.json'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      working-directory: vaspitac-app
      run: npm ci
      
    - name: Build Angular app
      working-directory: vaspitac-app
      run: npm run build
      
    - name: Sync Capacitor
      working-directory: vaspitac-app
      run: npx cap sync
      
    - name: Clean previous Android build
      working-directory: vaspitac-app/android
      run: ./gradlew clean
      
    - name: Build Android APK
      working-directory: vaspitac-app/android
      run: ./gradlew assembleDebug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: vaspitac-app-debug
        path: vaspitac-app/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30 