name: Build Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build-android-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'vaspitac-app/package-lock.json'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      working-directory: vaspitac-app
      run: npm ci

    - name: Create environment.ts from secrets for DEV
      working-directory: vaspitac-app
      run: |
        cat <<EOF > src/environments/environment.ts
        export const environment = {
          production: false,
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }
        }
        EOF

    - name: Build Angular app
      working-directory: vaspitac-app
      run: npm run build
      
    - name: Sync Capacitor
      working-directory: vaspitac-app
      run: npx cap sync

    - name: Create google-services.json from secret for DEV
      working-directory: vaspitac-app/android/app
      run: |
        echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

    - name: Make gradlew executable
      working-directory: vaspitac-app/android
      run: chmod +x gradlew
      
    - name: Clean previous Android build
      working-directory: vaspitac-app/android
      run: ./gradlew clean
      
    - name: Build Android APK
      working-directory: vaspitac-app/android
      run: ./gradlew assembleDevelopmentDebug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: vaspitac-app-debug-dev
        path: vaspitac-app/android/app/build/outputs/apk/development/debug/app-development-debug.apk
        retention-days: 30

    - name: Deploy Firebase to Development
      working-directory: vaspitac-app/firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        # Create service account key file
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > service-account-key.json
        
        # Set the environment variable to point to the service account file
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service-account-key.json"
        
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Set Firebase project to development (skip if fails)
        firebase use development || echo "Firebase project selection skipped"
        
        # Build functions if they exist
        if [ -d "functions" ]; then
          cd functions
          npm install
          npm run build
          cd ..
        fi
        
        # Deploy Firestore rules and indexes (skip if fails)
        firebase deploy --only firestore:rules,firestore:indexes --config firebase.dev.json || echo "Firestore deployment skipped due to permissions"
        
        # Deploy Storage rules (skip if fails)
        firebase deploy --only storage --config firebase.dev.json || echo "Storage deployment skipped due to permissions"
        
        # Deploy Functions if they exist (skip if fails)
        if [ -d "functions" ]; then
          firebase deploy --only functions --config firebase.dev.json || echo "Functions deployment skipped due to permissions"
        fi
        
        echo "Firebase deployment completed (some services may have been skipped due to permissions)"

  build-android-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'vaspitac-app/package-lock.json'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      working-directory: vaspitac-app
      run: npm ci

    - name: Create environment.ts from secrets for PROD
      working-directory: vaspitac-app
      run: |
        cat <<EOF > src/environments/environment.ts
        export const environment = {
          production: true,
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }
        }
        EOF

    - name: Build Angular app
      working-directory: vaspitac-app
      run: npm run build
      
    - name: Sync Capacitor
      working-directory: vaspitac-app
      run: npx cap sync

    - name: Create google-services.json from secret for PROD
      working-directory: vaspitac-app/android/app
      run: |
        echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

    - name: Make gradlew executable
      working-directory: vaspitac-app/android
      run: chmod +x gradlew
      
    - name: Clean previous Android build
      working-directory: vaspitac-app/android
      run: ./gradlew clean
      
    - name: Build Android APK
      working-directory: vaspitac-app/android
      run: ./gradlew assembleProductionDebug
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: vaspitac-app-debug-prod
        path: vaspitac-app/android/app/build/outputs/apk/production/debug/app-production-debug.apk
        retention-days: 30 

    - name: Deploy Firebase to Production
      working-directory: vaspitac-app/firebase
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        # Create service account key file
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > service-account-key.json
        
        # Set the environment variable to point to the service account file
        export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/service-account-key.json"
        
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Set Firebase project to production (skip if fails)
        firebase use production || echo "Firebase project selection skipped"
        
        # Build functions if they exist
        if [ -d "functions" ]; then
          cd functions
          npm install
          npm run build
          cd ..
        fi
        
        # Deploy Firestore rules and indexes (skip if fails)
        firebase deploy --only firestore:rules,firestore:indexes --config firebase.prod.json || echo "Firestore deployment skipped due to permissions"
        
        # Deploy Storage rules (skip if fails)
        firebase deploy --only storage --config firebase.prod.json || echo "Storage deployment skipped due to permissions"
        
        # Deploy Functions if they exist (skip if fails)
        if [ -d "functions" ]; then
          firebase deploy --only functions --config firebase.prod.json || echo "Functions deployment skipped due to permissions"
        fi
        
        echo "Firebase deployment completed (some services may have been skipped due to permissions)" 