name: Optimized Android Build

on:
  push:
    branches: [main, develop]
    paths:
      - 'vaspitac-app/src/**'
      - 'vaspitac-app/package.json'
      - 'vaspitac-app/package-lock.json'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # Android build jobs (parallel for different flavors)
  build-android-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Create environment configuration
        uses: ./.github/actions/create-environment
        with:
          environment: 'development'
          firebase-project: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          firebase-api-key: ${{ secrets.FIREBASE_API_KEY }}
          firebase-auth-domain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          firebase-storage-bucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          firebase-messaging-sender-id: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}
          firebase-measurement-id: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Build web application
        uses: ./.github/actions/build-web
        with:
          configuration: 'development'
          upload-artifact: 'false'

      - name: Setup Java and Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor
        working-directory: vaspitac-app
        run: npx cap sync

      - name: Create google-services.json
        working-directory: vaspitac-app/android/app
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON_DEV }}' > google-services.json

      - name: Build Android APK
        working-directory: vaspitac-app/android
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDevelopmentDebug
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaspitac-app-debug-dev
          path: vaspitac-app/android/app/build/outputs/apk/development/debug/app-development-debug.apk
          retention-days: 30

  build-android-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Create environment configuration
        uses: ./.github/actions/create-environment
        with:
          environment: 'production'
          firebase-project: ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase-api-key: ${{ secrets.FIREBASE_API_KEY }}
          firebase-auth-domain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          firebase-storage-bucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          firebase-messaging-sender-id: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}
          firebase-measurement-id: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Build web application
        uses: ./.github/actions/build-web
        with:
          configuration: 'production'
          upload-artifact: 'false'

      - name: Setup Java and Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor
        working-directory: vaspitac-app
        run: npx cap sync

      - name: Create google-services.json
        working-directory: vaspitac-app/android/app
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

      - name: Build Android APK
        working-directory: vaspitac-app/android
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleProductionDebug
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaspitac-app-debug-prod
          path: vaspitac-app/android/app/build/outputs/apk/production/debug/app-production-debug.apk
          retention-days: 30 