name: Optimized Android Build

on:
  push:
    branches: [main, develop]
    paths:
      - 'vaspitac-app/src/**'
      - 'vaspitac-app/package.json'
      - 'vaspitac-app/package-lock.json'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # Shared web build job
  build-web:
    runs-on: ubuntu-latest
    outputs:
      web-build-available: ${{ steps.build.outputs.available }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Setup Firebase
        uses: ./.github/actions/setup-firebase
        with:
          environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
          firebase-project: ${{ github.ref == 'refs/heads/main' && secrets.FIREBASE_PROJECT_ID || secrets.FIREBASE_PROJECT_ID_DEV }}
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Build web application
        id: build
        uses: ./.github/actions/build-web
        with:
          configuration: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
          upload-artifact: 'true'

  # Android build jobs (parallel for different flavors)
  build-android-dev:
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/develop' && needs.build-web.outputs.web-build-available == 'true'
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web-build-development
          path: vaspitac-app/dist/vaspitac-app

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Setup Firebase
        uses: ./.github/actions/setup-firebase
        with:
          environment: 'development'
          firebase-project: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Setup Java and Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor
        working-directory: vaspitac-app
        run: npx cap sync

      - name: Create google-services.json
        working-directory: vaspitac-app/android/app
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON_DEV }}' > google-services.json

      - name: Build Android APK
        working-directory: vaspitac-app/android
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDevelopmentDebug
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaspitac-app-debug-dev
          path: vaspitac-app/android/app/build/outputs/apk/development/debug/app-development-debug.apk
          retention-days: 30

  build-android-prod:
    runs-on: ubuntu-latest
    needs: build-web
    if: github.ref == 'refs/heads/main' && needs.build-web.outputs.web-build-available == 'true'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download web build
        uses: actions/download-artifact@v4
        with:
          name: web-build-production
          path: vaspitac-app/dist/vaspitac-app

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Setup Firebase
        uses: ./.github/actions/setup-firebase
        with:
          environment: 'production'
          firebase-project: ${{ secrets.FIREBASE_PROJECT_ID }}
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Setup Java and Android SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor
        working-directory: vaspitac-app
        run: npx cap sync

      - name: Create google-services.json
        working-directory: vaspitac-app/android/app
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > google-services.json

      - name: Build Android APK
        working-directory: vaspitac-app/android
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleProductionDebug
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: vaspitac-app-debug-prod
          path: vaspitac-app/android/app/build/outputs/apk/production/debug/app-production-debug.apk
          retention-days: 30 