name: Firebase Deploy Development

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  FIREBASE_PROJECT: ana-vaspitac-dev

jobs:
  # Security scan job (runs first)
  security-scan:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Run security scan
        uses: ./.github/actions/security-scan
        with:
          scan-dependencies: 'true'
          scan-code: 'true'

  # Build and test job
  build-and-test:
    runs-on: ubuntu-latest
    environment: development
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Create environment configuration
        uses: ./.github/actions/create-environment
        with:
          environment: 'development'
          firebase-project: ${{ env.FIREBASE_PROJECT }}
          firebase-api-key: ${{ secrets.FIREBASE_API_KEY }}
          firebase-auth-domain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          firebase-storage-bucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          firebase-messaging-sender-id: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}
          firebase-measurement-id: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Install dependencies
        working-directory: vaspitac-app
        run: npm ci
        
      - name: Run tests
        working-directory: vaspitac-app
        run: npm run test -- --browsers=ChromeHeadless --watch=false
        
      - name: Build application (Development)
        working-directory: vaspitac-app
        run: npm run build:dev
        
      - name: Verify build output
        working-directory: vaspitac-app
        run: |
          echo "🔍 Verifying build output..."
          ls -la dist/vaspitac-app/
          echo "📦 Build verification complete!"

  # Firebase hosting deployment job
  deploy-firebase-hosting:
    runs-on: ubuntu-latest
    environment: development
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Firebase Hosting
        uses: ./.github/actions/setup-firebase-hosting
        with:
          service-account-key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          project: ${{ env.FIREBASE_PROJECT }}

      - name: Deploy to Firebase Hosting
        uses: ./.github/actions/deploy-firebase-hosting
        with:
          working-directory: vaspitac-app

  # Final verification job
  verify-deployment:
    runs-on: ubuntu-latest
    needs: deploy-firebase-hosting
    environment: development
    steps:
      - name: Verify deployment
        run: |
          echo "🚀 Development deployment completed successfully!"
          echo "🌐 Development site: https://${{ env.FIREBASE_PROJECT }}.web.app"
          echo "✅ All checks passed!"
