name: TODO to Issue Automation

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs/TODO.md
          sparse-checkout-cone-mode: false

      - name: Create/update issues from TODO.md
        uses: meienberger/todo-to-issue@main
        with:
          todo-file: 'docs/TODO.md'
          id-pattern: '<!-- id: ([^ ]*) -->'
