name: TODO to Issue Automation

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            docs/TODO.md
          sparse-checkout-cone-mode: false

      - name: Show TODO.md content
        run: cat docs/TODO.md

      - name: Create/update issues from TODO.md
        uses: alstr/todo-to-issue-action@v4
        with:
          FILE_PATTERN: 'docs/TODO.md'
          ID_PATTERN: '<!-- id: ([^ ]*) -->'
