name: TODO to Issue Automation

on:
  push:
    branches:
      - main

jobs:
  todo:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Create/update issues from TODO.md
        uses: juulsn/todo-issue@latest
        with:
          file: TODO.md
          deduplicate: 'idTag'
