name: TODO to Issue Automation

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create/update issues from TODO.md
        uses: juulsn/todo-issue@v1.1.4
        with:
          file: TODO.md
          idTag: 'id'        # instruct the action to use <!-- id: ... --> tags for deduplication
