name: Test TODO to Issues

on:
  push:
    branches:
      - main

permissions:
  issues: write
  contents: read

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show TODO.md content
        run: cat TODO.md

      - name: Create/update issues from TODO.md
        uses: juulsn/todo-issue@v1.1.4
        with:
          label: 'todo-automation'
          autoAssign: false
          reopenClosed: false
