name: Optimized Unit Tests

on:
  push:
    branches: ["**"]
    paths:
      - 'vaspitac-app/src/**'
      - 'vaspitac-app/package.json'
      - 'vaspitac-app/package-lock.json'
  pull_request:
    branches: ["**"]
    paths:
      - 'vaspitac-app/src/**'
      - 'vaspitac-app/package.json'
      - 'vaspitac-app/package-lock.json'

jobs:
  # Security scan job
  security-scan:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Run security scan
        uses: ./.github/actions/security-scan
        with:
          scan-dependencies: 'true'
          scan-code: 'true'

  test:
    runs-on: ubuntu-latest
    environment: development
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/setup-node
        with:
          node-version: '18'

      - name: Create environment configuration
        uses: ./.github/actions/create-environment
        with:
          environment: 'development'
          firebase-project: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
          firebase-api-key: ${{ secrets.FIREBASE_API_KEY }}
          firebase-auth-domain: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          firebase-storage-bucket: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          firebase-messaging-sender-id: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          firebase-app-id: ${{ secrets.FIREBASE_APP_ID }}
          firebase-measurement-id: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Run unit tests with coverage
        working-directory: vaspitac-app
        run: npx ng test --browsers=ChromeHeadless --watch=false --code-coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: vaspitac-app/coverage/
          retention-days: 30

      - name: Fail if tests failed
        if: failure()
        run: exit 1 