name: Build Web App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'vaspitac-app/package-lock.json'

    - name: Install dependencies
      working-directory: vaspitac-app
      run: npm ci

    - name: Create environment.ts
      working-directory: vaspitac-app
      run: |
        # ⚠️ SECURITY: The API key will be visible in the compiled JS files
        # Ensure the FIREBASE_API_KEY secret has proper restrictions configured:
        # - HTTP referrers: your-domain.com, *.your-domain.com
        # - App package names: com.vaspitac.app (for Android)
        cat <<EOF > src/environments/environment.ts
        export const environment = {
          production: true,
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }
        }
        EOF

    - name: Build Angular app
      working-directory: vaspitac-app
      run: npm run build

    - name: Upload web build artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app-dist
        path: vaspitac-app/dist/vaspitac-app
        retention-days: 14 