name: Build Web App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-web-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'vaspitac-app/package-lock.json'

    - name: Install dependencies
      working-directory: vaspitac-app
      run: npm ci

    - name: Create environment.ts for DEV
      working-directory: vaspitac-app
      run: |
        cat <<EOF > src/environments/environment.ts
        export const environment = {
          production: false,
          environment: 'development',
          debugMode: true,
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }
        }
        EOF

    - name: Build Angular app
      working-directory: vaspitac-app
      run: npm run build

    - name: Upload web build artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app-dist-dev
        path: vaspitac-app/dist/vaspitac-app
        retention-days: 14

    - name: Deploy Firebase to Development
      working-directory: vaspitac-app/firebase
      run: |
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Set Firebase project to development
        firebase use development
        
        # Deploy Firestore rules and indexes
        firebase deploy --only firestore:rules,firestore:indexes --config firebase.dev.json --token "${{ secrets.FIREBASE_TOKEN }}"
        
        # Deploy Storage rules
        firebase deploy --only storage --config firebase.dev.json --token "${{ secrets.FIREBASE_TOKEN }}"
        
        # Deploy Functions if they exist
        if [ -d "functions" ]; then
          cd functions
          npm install
          cd ..
          firebase deploy --only functions --config firebase.dev.json --token "${{ secrets.FIREBASE_TOKEN }}"
        fi

  build-web-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'vaspitac-app/package-lock.json'

    - name: Install dependencies
      working-directory: vaspitac-app
      run: npm ci

    - name: Create environment.ts for PROD
      working-directory: vaspitac-app
      run: |
        cat <<EOF > src/environments/environment.ts
        export const environment = {
          production: true,
          environment: 'production',
          debugMode: false,
          firebase: {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}",
            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
          }
        }
        EOF

    - name: Build Angular app
      working-directory: vaspitac-app
      run: npm run build

    - name: Upload web build artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app-dist-prod
        path: vaspitac-app/dist/vaspitac-app
        retention-days: 14

    - name: Deploy Firebase to Production
      working-directory: vaspitac-app/firebase
      run: |
        # Install Firebase CLI
        npm install -g firebase-tools
        
        # Set Firebase project to production
        firebase use production
        
        # Deploy Firestore rules and indexes
        firebase deploy --only firestore:rules,firestore:indexes --config firebase.prod.json --token "${{ secrets.FIREBASE_TOKEN }}"
        
        # Deploy Storage rules
        firebase deploy --only storage --config firebase.prod.json --token "${{ secrets.FIREBASE_TOKEN }}"
        
        # Deploy Functions if they exist
        if [ -d "functions" ]; then
          cd functions
          npm install
          cd ..
          firebase deploy --only functions --config firebase.prod.json --token "${{ secrets.FIREBASE_TOKEN }}"
        fi 